name: cache


on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v3
    - name: Setup private repo credentials for private modules
      run: |
        git config --global user.name "jenkins-ecp-exa"
        git config --global user.email "jenkins-ecp-exa@exabeam.cloud"
        git config --global credential.username "jenkins-ecp-exa"
        git config --global credential.helper "store"
        git config --global url."https://token:${{ secrets.GH_TOKEN }}@github.com/${{ inputs.org }}".insteadOf "https://github.com/${{ inputs.org }}"
      shell: sh
    - name: gitconfig
      run: cat ~/.gitconfig
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}
        
    - name: npm install
      run: npm install
