name: cache


on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: Use Node.js 
      uses: actions/setup-node@v3
    - name: Setup private repo credentials for private modules
      run: |
        git config --global url."https://token:${{ secrets.GH_TOKEN }}@github.com".insteadOf "https://github.com/"
      shell: sh
    - name: gitconfig
      run: cat ~/.gitconfig
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}
        
    - name: npm install
      run: npm install --force
